version: "3.9"

services:
  admin_server:
    container_name: poker_admin
    build: .
    volumes: 
      - ./:/usr/src/app
      - admin_modules:/usr/src/app/node_modules
    environment: 
      - REDIS_HOST_NAME=redis
      - REDIS_PASSWORD=A2Dp/B0+b8BGpidH8I2FmBnSqAvFZeFNiDQezT6zQISEsK5V3wWQhDTtDM2mRKNacnA1KH8pWp9K4/Kg
    depends_on:
      - redis
    ports:
      - "3000:3000"
    networks:
      - "webnet"  

  redis:
    container_name: poker_redis
    image: redis:alpine
    command: redis-server --requirepass A2Dp/B0+b8BGpidH8I2FmBnSqAvFZeFNiDQezT6zQISEsK5V3wWQhDTtDM2mRKNacnA1KH8pWp9K4/Kg
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data
    networks:
      - "webnet"   

networks: 
  webnet:
    driver: bridge

volumes:
  admin_modules:
  redis_data:
